// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH-eK95sj3scVxqpQ6_NDViRoHv2_9yB4',
    appId: '1:760307854347:web:b27227d305289114922b0e',
    messagingSenderId: '760307854347',
    projectId: 'codex-mswhd',
    authDomain: 'codex-mswhd.firebaseapp.com',
    databaseURL: 'https://codex-mswhd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'codex-mswhd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGKeA5OPMgsKWOJn0wjIicAoq_V0MxEoI',
    appId: '1:760307854347:android:9fbf414d0eaeb786922b0e',
    messagingSenderId: '760307854347',
    projectId: 'codex-mswhd',
    databaseURL: 'https://codex-mswhd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'codex-mswhd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrRhfts8rsRj71WTkt0dEITM0J8T9lTWc',
    appId: '1:760307854347:ios:e35f4d8dd404422d922b0e',
    messagingSenderId: '760307854347',
    projectId: 'codex-mswhd',
    databaseURL: 'https://codex-mswhd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'codex-mswhd.appspot.com',
    iosClientId: '760307854347-18da90ruhdrn78h0fkv04jbhljkcdl53.apps.googleusercontent.com',
    iosBundleId: 'codex.mswhdAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrRhfts8rsRj71WTkt0dEITM0J8T9lTWc',
    appId: '1:760307854347:ios:e35f4d8dd404422d922b0e',
    messagingSenderId: '760307854347',
    projectId: 'codex-mswhd',
    databaseURL: 'https://codex-mswhd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'codex-mswhd.appspot.com',
    iosClientId: '760307854347-18da90ruhdrn78h0fkv04jbhljkcdl53.apps.googleusercontent.com',
    iosBundleId: 'codex.mswhdAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBH-eK95sj3scVxqpQ6_NDViRoHv2_9yB4',
    appId: '1:760307854347:web:ca7f82c3badd987d922b0e',
    messagingSenderId: '760307854347',
    projectId: 'codex-mswhd',
    authDomain: 'codex-mswhd.firebaseapp.com',
    databaseURL: 'https://codex-mswhd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'codex-mswhd.appspot.com',
  );
}
